# Buildspec file version: 0.2 to install apache httpd webserver Ubuntu as OS

version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo install APACHE - echo apt-get install APACHE
      - sudo apt-get update
      - sudo apt-get install apache2 -y
  build:
    commands:
      - echo Build started on date
      - cp -r ./* /usr/local/apache2/htdocs
  post_build:
    commands:
       - echo Configuring APACHE
artifacts:
  files:
    - "**/*"
